branch-defaults:
  default:
    environment: streamlit-env
    group_suffix: null
global:
  application_name: streamlit-eb-dashboard
  branch: null
  default_ec2_keyname: null
  default_platform: Python 3.12 running on 64bit Amazon Linux 2023
  default_region: eu-north-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: null
  workspace_type: Application
